### ISSUE TITLE
Can you also addin D2MultiRes and a mod that increase hireling slots that's compatitible with version 1.14D please?

### ISSUE THREAD

**Issue by DumbJoe** [sajonoso/d2mods#1]
800x600 resolution at full screen, even keeping aspect ratio looks too stretched out for me and would prefer a zoomed out effect so I could see even more surrounds to better give myself a tactical advantage as those mages and arches have done on me. The last version doesn't work on 1.14D so if you could find a copy of this somewhere or update it yourself so that it works for 1.14D that would be great! Naturally I don't want to downgrade version even if there is a way as I've heard it mentioned somewhere to get it working.

As for the hireling slots, well I wanted one of each from each area, or have more than one of each, say two rogues scouts or three rogues scouts and a desert mercenary so I could have more of a simulated party since I have no friends to play this game in multiplayer and or be bothered with it....apparently increasing party members also increases rate of experience gained so that could be a plus too!

**Comment by sajonoso** [comment]
Hi @DumbJoe, this project will be limited to text based mods only.  Adding more hirelings will require binary code edits.  Also, incorporating D2MultiRes into this project is out of scope.

However, I have updated the system so you can simulate a party (I have been working on this since last year).  You can now summon multiple creatures and have a new side kick that has the appearance of another hireling.  In total you can now have 1 hireling, 1 sidekick, mulitple Valkyries and depending on your character multiple golems and multiple bear and wolves.

**Comment by DumbJoe** [comment]
oh...ok...

does the multiple creatures and sidekick mod work for all characters or just a specific character class?

**Comment by sajonoso** [comment]
The multiple creatures and side kick works for any character provided you have the skill (or an item that grants you the skill) to summon them.  Enabling the sidekick or valkyrie mod adds a new Horadric cube recipe that can create a charm used to summon them.
